### PR TITLE
[WIP][SDK-2316] Update the Android and iOS SDKs

### PR DESCRIPTION
**Pull request by nsingh-branch**
## Reference
SDK-2316 -- .net maui update underlying native SDKs

## Summary
Updated the Android and iOS Branch SDK versions to the latest. Required updating some of the Android C# code and the Metadata.xml. 
Most of the changed files are from adding the new Branch iOS SDK, so collapsing the BranchSDK.iOSBinding makes it easier to see the actual changes.

## Motivation
Update the plugin to use the latest SDK features.

## Type Of Change

- [x] New feature (non-breaking change which adds functionality)

## Testing Instructions

Pack and integrate the updated SDK in a test app.

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by echo-branch** [comment]
Need to update the API definitions in both binding layers as the signatures have changed over the years. Also let's see if we can remove any that are not necessary at the C# layer. Many are technically public, but really only for our internal use cases.

**Comment by gdeluna-branch** [comment]
What's still needed on this PR?

**Comment by nsingh-branch** [comment]
> What's still needed on this PR?

The iOS SDK structure changed from v2 to v3, so it's causing problems when importing the Xamarin SDK into an app and trying to build. There's likely some sort of structure/configuration change required, but I wasn't able to find it before I had to move to a different project temporarily. I'll come back to this after though.

**Comment by ahmednawar** [comment]
Who can help with a review here?

**Comment by nsingh-branch** [comment]
> Who can help with a review here?

It's on hold at the moment since I had to switch to other high-pri work. But I'm going to be coming back to it later this month.

**Pull request closed without merging**
